// Sample marketplace data — demo/preview only
// All names, contacts, and details are fictional placeholders

export const PLACEMENT_ORDER = [
  'Exclusive Category Partner',
  'Category Member',
  'Visibility Member',
  'Community Member',
];

export const CATEGORY_ORDER = [
  'Accounting',
  'Bookkeeping',
  'Finance',
  'Insurance',
  'Legal / Compliance',
  'Payroll',
  'Marketing / Branding',
  'Printing / Branding',
  'Web Services',
  'Technology Services',
  'Business Consulting',
  'Operations Support',
  'Cleaning Services',
  'Construction / Trades',
  'Logistics',
  'Real Estate',
  'Staffing / Recruiting',
  'Property Services',
  'Health / Wellness',
  'Commercial Services',
  'General Business',
  'Other Professional Services',
];

export const SERVICE_TYPES = [
  'All Service Types',
  'Finance / Accounting',
  'Legal / Compliance',
  'Marketing / Branding',
  'Technology',
  'Business Operations',
  'Construction / Trades',
  'Home / Property Services',
  'Health / Wellness',
  'Logistics / Transportation',
  'Staffing / Recruiting',
  'Professional Services',
  'Other',
];

export const members = [
  // ─── EXCLUSIVE CATEGORY PARTNERS ────────────────────────────────────────────
  {
    id: 1,
    business: 'Apex Ledger Group',
    contact: 'James Rowan',
    level: 'Exclusive Category Partner',
    category: 'Accounting',
    serviceType: 'Finance / Accounting',
    chapter: 'The Link Houston',
    market: 'Houston, TX',
    serviceArea: 'Greater Houston Region',
    description: 'Full-service accounting firm specializing in small business tax preparation, bookkeeping, financial reporting, and CFO advisory services for owner-operated businesses.',
    whoWeHelp: 'Small business owners, service providers, and solo operators who need reliable accounting, clean books, and tax strategy.',
    bestFit: 'Business owners looking for a long-term accounting partner who understands small business operations.',
    phone: '(example) 281-555-0110',
    email: 'info@apexledgergroup.com',
    website: 'apexledgergroup.com',
  },
  {
    id: 2,
    business: 'BrightPath Commercial Cleaning',
    contact: 'Maria Santos',
    level: 'Exclusive Category Partner',
    category: 'Cleaning Services',
    serviceType: 'Home / Property Services',
    chapter: 'The Link Gulf Coast',
    market: 'Houston, TX',
    serviceArea: 'Gulf Coast Region',
    description: 'Commercial cleaning services for offices, retail locations, medical facilities, and multi-tenant properties. Regular contracts and one-time deep cleans available.',
    whoWeHelp: 'Property managers, office tenants, retail owners, and facility managers who need dependable commercial cleaning on a schedule.',
    bestFit: 'Best introduction: property managers, office managers, or business owners with a physical location.',
    phone: '(example) 713-555-0142',
    email: 'info@brightpathcleaning.com',
    website: 'brightpathcleaning.com',
  },
  {
    id: 3,
    business: 'Cornerstone Web Studio',
    contact: 'Derek Hall',
    level: 'Exclusive Category Partner',
    category: 'Web Services',
    serviceType: 'Technology',
    chapter: 'The Link Houston',
    market: 'The Woodlands, TX',
    serviceArea: 'Greater Houston / Montgomery County',
    description: 'Web design, development, and digital presence services for small businesses. Specializes in service-based business websites, local SEO, and online profile builds.',
    whoWeHelp: 'Small business owners who need a professional online presence, a redesigned website, or local search visibility.',
    bestFit: 'Best fit: service businesses, trades, and professional service providers who need to be found online.',
    phone: '(example) 281-555-0187',
    email: 'hello@cornerstonewebstudio.com',
    website: 'cornerstonewebstudio.com',
  },

  // ─── CATEGORY MEMBERS ───────────────────────────────────────────────────────
  {
    id: 4,
    business: 'Bayview Insurance Advisors',
    contact: 'Sandra Kim',
    level: 'Category Member',
    category: 'Insurance',
    serviceType: 'Finance / Accounting',
    chapter: 'The Link Montgomery County',
    market: 'Conroe, TX',
    serviceArea: 'Montgomery County / Greater Houston',
    description: 'Commercial and personal insurance advisory services for small business owners. Coverage includes general liability, business owners policy (BOP), workers comp, and professional liability.',
    whoWeHelp: 'Business owners who need insurance guidance, coverage reviews, or are setting up a new business and need to understand their options.',
    bestFit: 'Best introduction: any business owner looking for insurance coverage, a second opinion on current policy, or first-time business insurance setup.',
    phone: '(example) 936-555-0133',
    email: 'info@bayviewinsurance.com',
    website: 'bayviewinsurance.com',
  },
  {
    id: 5,
    business: 'ClearPath Business Consulting',
    contact: 'Anthony Reeves',
    level: 'Category Member',
    category: 'Business Consulting',
    serviceType: 'Business Operations',
    chapter: 'The Link The Woodlands',
    market: 'The Woodlands, TX',
    serviceArea: 'Greater Houston / North Houston Suburbs',
    description: 'Business consulting for small to mid-size businesses. Focus areas: operational efficiency, growth planning, process documentation, and owner-level advisory.',
    whoWeHelp: 'Business owners who feel stuck, disorganized, or ready to grow but unsure where to focus. Also works with owners preparing to hire.',
    bestFit: 'Best fit: owner-operators who want to build systems, improve operations, or plan for growth.',
    phone: '(example) 281-555-0155',
    email: 'anthony@clearpath-consulting.com',
    website: 'clearpath-consulting.com',
  },
  {
    id: 6,
    business: 'Gulf Coast Payroll Services',
    contact: 'Denise Carter',
    level: 'Category Member',
    category: 'Payroll',
    serviceType: 'Finance / Accounting',
    chapter: 'The Link Houston',
    market: 'Houston, TX',
    serviceArea: 'Greater Houston Region',
    description: 'Payroll processing, compliance, and HR administration for small businesses. Handles direct deposit, tax filings, W-2s, and new hire paperwork.',
    whoWeHelp: 'Business owners with 1–25 employees who want accurate payroll without managing it themselves.',
    bestFit: 'Best introduction: any business owner who has or is hiring employees and needs payroll handled correctly.',
    phone: '(example) 713-555-0198',
    email: 'info@gulfcoastpayroll.com',
    website: 'gulfcoastpayroll.com',
  },

  // ─── VISIBILITY MEMBERS ─────────────────────────────────────────────────────
  {
    id: 7,
    business: 'ABC Print & Branding',
    contact: 'Kevin Torres',
    level: 'Visibility Member',
    category: 'Printing / Branding',
    serviceType: 'Marketing / Branding',
    chapter: 'The Link Magnolia',
    market: 'Magnolia, TX',
    serviceArea: 'Magnolia / Northwest Houston',
    description: 'Print services, branded materials, and signage for local businesses. Business cards, banners, branded merch, vehicle magnets, and more.',
    whoWeHelp: 'Local businesses that need print collateral, event signage, branded materials, or a brand refresh on printed items.',
    bestFit: 'Best fit: businesses opening a new location, attending events, or rebranding and needing updated print materials.',
    phone: '(example) 281-555-0171',
    email: 'info@abcprintbranding.com',
    website: 'abcprintbranding.com',
  },
  {
    id: 8,
    business: 'Better Choice Staffing',
    contact: 'Lisa Nguyen',
    level: 'Visibility Member',
    category: 'Staffing / Recruiting',
    serviceType: 'Staffing / Recruiting',
    chapter: 'The Link Houston',
    market: 'Houston, TX',
    serviceArea: 'Greater Houston Region',
    description: 'Staffing and recruiting services for small and mid-size businesses. Specializes in administrative, customer service, light industrial, and entry-level professional placements.',
    whoWeHelp: 'Business owners who need to hire but do not have time to recruit, screen, and onboard candidates.',
    bestFit: 'Best introduction: business owners who are hiring or planning to hire in the next 60–90 days.',
    phone: '(example) 713-555-0119',
    email: 'info@betterchoicestaffing.com',
    website: 'betterchoicestaffing.com',
  },
  {
    id: 9,
    business: 'Lone Star Property Services',
    contact: 'Brian Walsh',
    level: 'Visibility Member',
    category: 'Property Services',
    serviceType: 'Home / Property Services',
    chapter: 'The Link Gulf Coast',
    market: 'Houston, TX',
    serviceArea: 'Gulf Coast / Southeast Houston',
    description: 'Property maintenance and repair services for landlords, property managers, and commercial tenants. Handyman work, light renovation, landscaping coordination, and general upkeep.',
    whoWeHelp: 'Property owners, real estate investors, and commercial tenants who need reliable property maintenance without managing multiple vendors.',
    bestFit: 'Best fit: real estate investors, landlords, and property managers with multiple locations or recurring maintenance needs.',
    phone: '(example) 713-555-0164',
    email: 'info@lonestarpropertyservices.com',
    website: 'lonestarpropertyservices.com',
  },

  // ─── COMMUNITY MEMBERS ──────────────────────────────────────────────────────
  {
    id: 10,
    business: 'Blue Oak Services',
    contact: 'Marcus Bell',
    level: 'Community Member',
    category: 'General Business',
    serviceType: 'Professional Services',
    chapter: 'The Link Houston',
    market: 'Houston, TX',
    serviceArea: 'Greater Houston',
    description: 'General business support services for small business owners. Errand services, business coordination, and administrative support for busy owner-operators.',
    whoWeHelp: 'Small business owners who need extra hands for administrative, coordination, or operational tasks.',
    bestFit: 'Best fit: solo operators and small business owners who need flexible support without a full-time hire.',
    phone: '(example) 713-555-0177',
    email: 'info@blueoakservices.com',
    website: 'blueoakservices.com',
  },
  {
    id: 11,
    business: 'Main Street Vendors Co.',
    contact: 'Patricia Moore',
    level: 'Community Member',
    category: 'General Business',
    serviceType: 'Professional Services',
    chapter: 'The Link Montgomery County',
    market: 'Conroe, TX',
    serviceArea: 'Montgomery County',
    description: 'Local vendor services for events, markets, and pop-up opportunities. Connects local vendors with events and helps small businesses participate in community commerce.',
    whoWeHelp: 'Local vendors, artisans, and small businesses looking for event and market opportunities in Montgomery County.',
    bestFit: 'Best introduction: event organizers, market coordinators, or business owners interested in local vendor opportunities.',
    phone: '(example) 936-555-0149',
    email: 'info@mainstreetvendors.com',
    website: 'mainstreetvendors.com',
  },
  {
    id: 12,
    business: 'Northline Support Group',
    contact: 'David Chen',
    level: 'Community Member',
    category: 'General Business',
    serviceType: 'Business Operations',
    chapter: 'The Link The Woodlands',
    market: 'The Woodlands, TX',
    serviceArea: 'North Houston / The Woodlands',
    description: 'General business support including virtual assistant services, scheduling coordination, and back-office support for small business owners.',
    whoWeHelp: 'Entrepreneurs and solo operators who need part-time administrative or operations support.',
    bestFit: 'Best fit: busy owner-operators who need consistent back-office help without a full-time employee.',
    phone: '(example) 281-555-0183',
    email: 'info@northlinesupport.com',
    website: 'northlinesupport.com',
  },
];

export const CHAPTERS = ['All Chapters', ...Array.from(new Set(members.map(m => m.chapter)))];
export const MARKETS = ['All Markets', ...Array.from(new Set(members.map(m => m.market)))];
export const CATEGORIES_LIST = ['All Categories', ...CATEGORY_ORDER.filter(c => members.some(m => m.category === c))];
export const LEVELS_LIST = ['All Levels', ...PLACEMENT_ORDER];