// ─────────────────────────────────────────────────────────────────────────────
// Link Business Alliance — Centralized Page Content
// Edit H1s, subtext, SEO titles, meta descriptions, hero images, and CTAs here.
// ─────────────────────────────────────────────────────────────────────────────

export const pageContent = {
  home: {
    path: '/',
    seoTitle: 'Link Business Alliance | Business Owner Network, Resources & Local Chapters',
    metaDescription: 'Link Business Alliance helps business owners connect with trusted people, resources, local opportunities, member visibility, and practical support through The Link.',
    eyebrow: 'Link Business Alliance',
    h1: 'Business Owners Should Not Have to Build Alone.',
    subtext: 'Link Business Alliance helps owners connect with the right people, find trusted resources, understand local opportunities, become visible in the business community, and build stronger businesses through a structured member network.',
    heroImage: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1920&q=80',
    heroAlt: 'Business owners collaborating in a professional meeting',
    overlayStrength: 'light',
    primaryCta: { label: 'Find Your Local Link', route: '/find-chapter' },
    secondaryCta: { label: 'Compare Membership Options', route: '/membership' },
    tertiaryCta: { label: 'Start a Chapter', route: '/start-chapter' },
  },
  about: {
    path: '/about',
    seoTitle: 'About The Link | Business Owner Alliance Built for Practical Support',
    metaDescription: 'Learn about Link Business Alliance — a structured business-owner alliance built to help owners connect, learn, find resources, and grow with practical local support.',
    eyebrow: 'About The Link',
    h1: 'Built for Business Owners Who Want to Build With Support.',
    subtext: 'The Link exists to help owners stop operating alone by giving them access to relationships, resources, practical knowledge, visibility, and local opportunities through a structured business-owner alliance.',
    heroImage: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1920&q=80',
    heroAlt: 'Business owners in a professional meeting and collaboration setting',
    primaryCta: { label: 'Learn How The Link Helps', route: '/membership' },
  },
  membership: {
    path: '/membership',
    seoTitle: 'Membership | Link Business Alliance Plans for Business Owners',
    metaDescription: 'Explore Link Business Alliance membership plans — Community, Visibility, Category, and Exclusive Category Partner. Find the right level for your business stage.',
    eyebrow: 'Membership',
    h1: 'Membership Built for Every Stage of Business.',
    subtext: 'Whether you are just starting out, growing a local company, or ready for stronger category visibility, The Link gives owners practical ways to connect, learn, and grow with support.',
    heroImage: 'https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?auto=format&fit=crop&w=1920&q=80',
    heroAlt: 'Business owner reviewing membership options with a team member',
    primaryCta: { label: 'Compare Membership Options', route: '#pricing' },
    secondaryCta: { label: 'Ask About Membership', route: '/ask-about-membership' },
  },
  findChapter: {
    path: '/find-chapter',
    seoTitle: 'Find a Chapter | Local Business Owner Networking with The Link',
    metaDescription: 'Find a Link Business Alliance chapter near you. Connect with local business owners, access resources, attend events, and build relationships in your market.',
    eyebrow: 'Local Chapters',
    h1: 'Find Your Local Link.',
    subtext: 'Connect with business owners, resources, events, and opportunities through a local Link chapter in your market.',
    heroImage: 'https://images.unsplash.com/photo-1543269664-56d93c1b41a6?auto=format&fit=crop&w=1920&q=80',
    heroAlt: 'Local business owners meeting and networking in a community setting',
    primaryCta: { label: 'Search Chapters', route: '#chapters' },
    secondaryCta: { label: 'Start a Chapter', route: '/start-chapter' },
  },
  startChapter: {
    path: '/start-chapter',
    seoTitle: 'Start a Chapter | Build a Local Business Owner Alliance',
    metaDescription: 'Start a Link Business Alliance chapter in your local market. Help business owners connect, access resources, attend events, and build stronger community through The Link.',
    eyebrow: 'Chapter Opportunity',
    h1: 'Start a Link Chapter in Your Market.',
    subtext: 'Qualified local leaders can help build a structured business-owner community that connects members, resources, education, visibility, and local opportunities.',
    heroImage: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1920&q=80',
    heroAlt: 'Community business leaders organizing a local chapter meeting',
    primaryCta: { label: 'Apply to Start a Chapter', route: '#apply' },
    secondaryCta: { label: 'Talk to The Link', route: '/contact' },
  },
  events: {
    path: '/events',
    seoTitle: 'Events | Business Owner Roundtables, Networking & Resource Sessions',
    metaDescription: 'Attend Link Business Alliance chapter meetings, owner roundtables, education sessions, and networking events. Real business owners. Practical discussions.',
    eyebrow: 'Events',
    h1: 'Meet, Learn, and Build Real Business Relationships.',
    subtext: 'The Link events bring owners together through chapter meetings, roundtables, resource sessions, member introductions, and practical business education.',
    heroImage: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1920&q=80',
    heroAlt: 'Business owners at a professional networking and education event',
    primaryCta: { label: 'View Upcoming Events', route: '#events-list' },
    secondaryCta: { label: 'RSVP for an Event', route: '/event-rsvp' },
    tertiaryCta: { label: 'Sponsor an Event', route: '/sponsor-inquiry' },
  },
  education: {
    path: '/education',
    seoTitle: 'Business Education | Practical Resources for Small Business Owners',
    metaDescription: 'Access practical business education from Link Business Alliance — owner-led sessions, guides, and discussions designed to help small business owners make better decisions.',
    eyebrow: 'Business Education',
    h1: 'Practical Business Education From People Who Have Been There.',
    subtext: 'Access owner-focused sessions, guides, and discussions designed to help members avoid common mistakes and make better business decisions.',
    heroImage: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1920&q=80',
    heroAlt: 'Business owner presenting practical education to a small group',
    primaryCta: { label: 'Explore Education', route: '#curriculum' },
    secondaryCta: { label: 'View Resources', route: '/resources' },
  },
  mentorship: {
    path: '/mentorship',
    seoTitle: 'Mentorship | Owner-to-Owner Guidance for Business Builders',
    metaDescription: 'Connect with experienced business owners through Link Business Alliance mentorship. Real guidance from owners who understand the challenges of building and running a business.',
    eyebrow: 'Mentorship',
    h1: 'Learn From Experienced Business Owners.',
    subtext: 'The Link mentorship model helps members learn from owners and operators who understand the real challenges of building and running a business.',
    heroImage: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1920&q=80',
    heroAlt: 'Experienced business owner mentoring a newer entrepreneur',
    primaryCta: { label: 'Ask About Mentorship', route: '/contact' },
    secondaryCta: { label: 'Join The Link', route: '/join' },
  },
  directory: {
    path: '/directory',
    seoTitle: 'Member Directory | Find Link Business Alliance Members by Category',
    metaDescription: 'Search the Link Business Alliance member directory by membership placement, category, chapter, service area, and business name.',
    eyebrow: 'Member Directory',
    h1: 'Find Link Members by Plan, Category, and Market.',
    subtext: 'Search member businesses by membership placement, category, chapter, service area, and business name.',
    heroImage: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?auto=format&fit=crop&w=1920&q=80',
    heroAlt: 'Professional business directory and member network overview',
    primaryCta: { label: 'Search Directory', route: '#search' },
    secondaryCta: { label: 'List Your Business', route: '/list-your-business' },
  },
  marketplace: {
    path: '/marketplace',
    seoTitle: 'Marketplace | Member Services and Local Business Support',
    metaDescription: 'Find member services, local business support, and professional service providers through the Link Business Alliance member services marketplace.',
    eyebrow: 'Marketplace',
    h1: 'Discover Member Services and Local Business Support.',
    subtext: 'The Link Marketplace helps members and visitors find services, offers, providers, and business support available through Link Business Alliance members.',
    heroImage: 'https://images.unsplash.com/photo-1444653614773-995cb1ef9efa?auto=format&fit=crop&w=1920&q=80',
    heroAlt: 'Business owners discussing services and local commerce partnerships',
    primaryCta: { label: 'Explore Member Services', route: '#showcase' },
    secondaryCta: { label: 'List Your Services', route: '/list-your-services' },
  },
  resources: {
    path: '/resources',
    seoTitle: 'Resources | Small Business Guides, Checklists and Templates',
    metaDescription: 'Find checklists, guides, templates, tools, and practical resources for small business owners through the Link Business Alliance resource library.',
    eyebrow: 'Resources',
    h1: 'Find Practical Resources for Your Business Stage.',
    subtext: 'Use The Link resource library to find checklists, guides, templates, tools, and local support based on where you are in business and what you need help with.',
    heroImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1920&q=80',
    heroAlt: 'Business owner reviewing practical guides and business resources',
    primaryCta: { label: 'Browse Resources', route: '#library' },
    secondaryCta: { label: 'Take the Readiness Quiz', route: '/member-readiness-quiz' },
  },
  partners: {
    path: '/partners',
    seoTitle: 'Partners | Sponsor and Support Local Business Owner Chapters',
    metaDescription: 'Partner with Link Business Alliance to support local business owners through chapter sponsorships, member benefits, and strategic partnership opportunities.',
    eyebrow: 'Partners',
    h1: 'Partner With a Business-Owner Alliance Built for Local Impact.',
    subtext: 'Sponsors and partners help support local chapters, member education, events, resources, and business-owner visibility.',
    heroImage: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?auto=format&fit=crop&w=1920&q=80',
    heroAlt: 'Business partners shaking hands in a professional meeting setting',
    primaryCta: { label: 'Become a Partner', route: '#partner-form' },
    secondaryCta: { label: 'Sponsor a Chapter', route: '/sponsor-inquiry' },
  },
  successStories: {
    path: '/success-stories',
    seoTitle: 'Success Stories | Business Owners Building With Support',
    metaDescription: 'Read how business owners use Link Business Alliance relationships, resources, visibility, and practical support to become better connected and more prepared to grow.',
    eyebrow: 'Success Stories',
    h1: 'Stories From Owners Building With Support.',
    subtext: 'See how business owners use relationships, resources, visibility, and practical support to become better connected and better prepared to grow.',
    heroImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1920&q=80',
    heroAlt: 'Business owner sharing their success and growth story',
    primaryCta: { label: 'Share Your Story', route: '/contact' },
    secondaryCta: { label: 'Join The Link', route: '/join' },
  },
  blog: {
    path: '/blog',
    seoTitle: 'Blog | Practical Insights for Business Owners and Entrepreneurs',
    metaDescription: 'Read practical articles on business ownership, local visibility, resources, relationships, member readiness, and business growth through support.',
    eyebrow: 'Insights',
    h1: 'Insights for Business Owners Who Do Not Want to Build Alone.',
    subtext: 'Read practical articles on business ownership, local visibility, resources, relationships, member readiness, and business growth through support.',
    heroImage: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=1920&q=80',
    heroAlt: 'Business owner reading practical business insights and articles',
    primaryCta: { label: 'Read Articles', route: '#articles' },
    secondaryCta: { label: 'Explore Resources', route: '/resources' },
  },
  contact: {
    path: '/contact',
    seoTitle: 'Contact Link Business Alliance | Membership, Chapters and Partnerships',
    metaDescription: 'Contact Link Business Alliance to ask about membership, find a chapter, list your business, sponsor a local market, or start a chapter.',
    eyebrow: 'Contact',
    h1: 'Tell Us What You Need Help With.',
    subtext: 'Whether you want to join, find a chapter, list your business, sponsor a local market, or start a chapter, The Link can help point you in the right direction.',
    heroImage: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1920&q=80',
    heroAlt: 'Business team in a professional meeting ready to help',
    primaryCta: { label: 'Send Inquiry', route: '#contact-form' },
    secondaryCta: { label: 'Take Readiness Quiz', route: '/member-readiness-quiz' },
  },
  readinessQuiz: {
    path: '/member-readiness-quiz',
    seoTitle: 'Member Readiness Quiz | Link Business Alliance',
    metaDescription: 'Take the Link Business Alliance member readiness quiz to see if your business is ready for member visibility, introductions, directory placement, and chapter participation.',
    eyebrow: 'Member Readiness',
    h1: 'Is Your Business Ready to Get the Most From The Link?',
    subtext: 'Use this quick checklist to see whether your business is ready for member visibility, introductions, directory placement, and chapter participation.',
    heroImage: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=1920&q=80',
    heroAlt: 'Business owner completing a readiness assessment checklist',
    primaryCta: { label: 'Start the Quiz', route: '#quiz' },
  },
  join: {
    path: '/join',
    seoTitle: 'Join The Link | Start Your Link Business Alliance Membership',
    metaDescription: 'Join Link Business Alliance and connect with local business owners, resources, chapters, and practical support through The Link.',
    eyebrow: 'Join The Link',
    h1: 'Start Your Link Membership.',
    subtext: 'Tell us about your business and we\'ll connect you with the right chapter, membership level, and resources.',
    heroImage: 'https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?auto=format&fit=crop&w=1920&q=80',
    heroAlt: 'Business owner joining a professional network',
    primaryCta: { label: 'Complete Inquiry', route: '#join-form' },
  },
  faq: {
    path: '/faq',
    seoTitle: 'FAQ | Link Business Alliance Membership, Directory & Chapters',
    metaDescription: 'Find answers to common questions about Link Business Alliance membership levels, directory placement, chapters, events, resources, and joining.',
    eyebrow: 'FAQ',
    h1: 'Frequently Asked Questions.',
    subtext: 'Find answers about membership levels, directory placement, chapters, events, and joining The Link.',
    heroImage: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1920&q=80',
    heroAlt: 'Business owner reviewing frequently asked questions about a professional network',
    primaryCta: { label: 'Browse Questions', route: '#faq' },
    secondaryCta: { label: 'Contact Us', route: '/contact' },
  },
  growthCaseStudies: {
    path: '/growth-case-studies',
    seoTitle: 'Growth Case Studies | How Business Owners Use The Link',
    metaDescription: 'See structured case studies showing how Link Business Alliance members have used relationships, resources, visibility, and chapter support to address real business challenges.',
    eyebrow: 'Growth Case Studies',
    h1: 'How Business Owners Use The Link to Build.',
    subtext: 'Structured examples of how Link members have used relationships, resources, visibility, and chapter support to address real business challenges.',
    heroImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1920&q=80',
    heroAlt: 'Business owners reviewing growth strategies and case studies',
    primaryCta: { label: 'Read Case Studies', route: '#case-studies' },
    secondaryCta: { label: 'Join The Link', route: '/join' },
  },
  memberDashboard: {
    path: '/member-dashboard',
    seoTitle: 'Member Dashboard | Link Business Alliance',
    metaDescription: 'Access your Link Business Alliance member tools — profile, events, chapter resources, directory listing, and marketplace from one place.',
    eyebrow: 'Member Dashboard',
    h1: 'Welcome to Your Link Dashboard.',
    subtext: 'Access your profile, chapter events, resources, directory listing, and member tools from one place.',
    heroImage: 'https://images.unsplash.com/photo-1664575602554-2087b04935a5?auto=format&fit=crop&w=1920&q=80',
    heroAlt: 'Business owner reviewing member resources and tools at a professional workstation',
    primaryCta: { label: 'Browse Resources', route: '/resources' },
    secondaryCta: { label: 'View Events', route: '/events' },
  },
  eventRsvp: {
    path: '/event-rsvp',
    seoTitle: 'Event RSVP | Link Business Alliance Chapter Meetings and Roundtables',
    metaDescription: 'RSVP for a Link Business Alliance event — chapter meetings, owner roundtables, education sessions, sponsor events, and member introduction events.',
    eyebrow: 'Event RSVP',
    h1: 'RSVP for a Link Event.',
    subtext: 'Let us know which event you are interested in and we will follow up with details, confirmation, and any event-specific information.',
    heroImage: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1920&q=80',
    heroAlt: 'Business owners at a professional networking and education event',
    primaryCta: { label: 'Complete RSVP', route: '#rsvp-form' },
    secondaryCta: { label: 'View Events', route: '/events' },
  },
};